### ISSUE TITLE
Exception using generator - cannot find module ../../util.js

### ISSUE THREAD

**Issue by mtebong** [kevinpirola/generator-full-separated-angular-spring#1]
$ yo full-separated-angular-spring
module.js:471
    throw err;
    ^

Error: Cannot find module '../../util.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\mark-andrew.t.tebong\AppData\Roaming\npm\nod                   e_modules\generator-full-separated-angular-spring\generators\app\index.js:5:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**npm version: 3.10.8
yo version: 1.8.5**

**Comment by kevinpirola** [comment]
Thank you for your message, I will check this as soon as possible.

**Comment by kevinpirola** [comment]
In the meantime can you try to uninstall the generator and reinstall it with:

```npm install --global --verbose generator-full-separated-angular-spring ```

and paste the log here?

**Comment by kevinpirola** [comment]
Fixed in version 0.0.3

Closing.
